spring:
  datasource:
    url: jdbc:mysql://localhost:3306/test_java6
    username: root
    password: root

  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
        ddl-auto: update
